export interface Country {
  code: string   // ISO 3166-1 alpha-2
  name: string
  flag: string   // Unicode flag emoji
  phone: string  // Dialing prefix (e.g. "+1")
  states?: string[]
}

export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", flag: "🇦🇫", phone: "+93" },
  { code: "AL", name: "Albania", flag: "🇦🇱", phone: "+355" },
  { code: "DZ", name: "Algeria", flag: "🇩🇿", phone: "+213", states: ["Adrar","Aïn Defla","Aïn Témouchent","Algiers","Annaba","Batna","Béchar","Béjaïa","Biskra","Blida","Bordj Bou Arréridj","Bouira","Boumerdès","Chlef","Constantine","Djelfa","El Bayadh","El Oued","El Tarf","Ghardaïa","Guelma","Illizi","Jijel","Khenchela","Laghouat","Mascara","Médéa","Mila","Mostaganem","Msila","Naâma","Oran","Ouargla","Oum El Bouaghi","Relizane","Saïda","Sétif","Sidi Bel Abbès","Skikda","Souk Ahras","Tamanghasset","Tébessa","Tiaret","Tindouf","Tipaza","Tissemsilt","Tizi Ouzou","Tlemcen"] },
  { code: "AD", name: "Andorra", flag: "🇦🇩", phone: "+376" },
  { code: "AO", name: "Angola", flag: "🇦🇴", phone: "+244" },
  { code: "AG", name: "Antigua and Barbuda", flag: "🇦🇬", phone: "+1" },
  { code: "AR", name: "Argentina", flag: "🇦🇷", phone: "+54", states: ["Buenos Aires","Buenos Aires City","Catamarca","Chaco","Chubut","Córdoba","Corrientes","Entre Ríos","Formosa","Jujuy","La Pampa","La Rioja","Mendoza","Misiones","Neuquén","Río Negro","Salta","San Juan","San Luis","Santa Cruz","Santa Fe","Santiago del Estero","Tierra del Fuego","Tucumán"] },
  { code: "AM", name: "Armenia", flag: "🇦🇲", phone: "+374" },
  { code: "AU", name: "Australia", flag: "🇦🇺", phone: "+61", states: ["Australian Capital Territory","New South Wales","Northern Territory","Queensland","South Australia","Tasmania","Victoria","Western Australia"] },
  { code: "AT", name: "Austria", flag: "🇦🇹", phone: "+43", states: ["Burgenland","Carinthia","Lower Austria","Salzburg","Styria","Tyrol","Upper Austria","Vienna","Vorarlberg"] },
  { code: "AZ", name: "Azerbaijan", flag: "🇦🇿", phone: "+994" },
  { code: "BS", name: "Bahamas", flag: "🇧🇸", phone: "+1" },
  { code: "BH", name: "Bahrain", flag: "🇧🇭", phone: "+973" },
  { code: "BD", name: "Bangladesh", flag: "🇧🇩", phone: "+880", states: ["Barisal","Chittagong","Dhaka","Khulna","Mymensingh","Rajshahi","Rangpur","Sylhet"] },
  { code: "BB", name: "Barbados", flag: "🇧🇧", phone: "+1" },
  { code: "BY", name: "Belarus", flag: "🇧🇾", phone: "+375" },
  { code: "BE", name: "Belgium", flag: "🇧🇪", phone: "+32", states: ["Antwerp","Brussels","East Flanders","Flemish Brabant","Hainaut","Liège","Limburg","Luxembourg","Namur","Walloon Brabant","West Flanders"] },
  { code: "BZ", name: "Belize", flag: "🇧🇿", phone: "+501" },
  { code: "BJ", name: "Benin", flag: "🇧🇯", phone: "+229" },
  { code: "BT", name: "Bhutan", flag: "🇧🇹", phone: "+975" },
  { code: "BO", name: "Bolivia", flag: "🇧🇴", phone: "+591" },
  { code: "BA", name: "Bosnia and Herzegovina", flag: "🇧🇦", phone: "+387" },
  { code: "BW", name: "Botswana", flag: "🇧🇼", phone: "+267" },
  { code: "BR", name: "Brazil", flag: "🇧🇷", phone: "+55", states: ["Acre","Alagoas","Amapá","Amazonas","Bahia","Ceará","Distrito Federal","Espírito Santo","Goiás","Maranhão","Mato Grosso","Mato Grosso do Sul","Minas Gerais","Pará","Paraíba","Paraná","Pernambuco","Piauí","Rio de Janeiro","Rio Grande do Norte","Rio Grande do Sul","Rondônia","Roraima","Santa Catarina","São Paulo","Sergipe","Tocantins"] },
  { code: "BN", name: "Brunei", flag: "🇧🇳", phone: "+673" },
  { code: "BG", name: "Bulgaria", flag: "🇧🇬", phone: "+359" },
  { code: "BF", name: "Burkina Faso", flag: "🇧🇫", phone: "+226" },
  { code: "BI", name: "Burundi", flag: "🇧🇮", phone: "+257" },
  { code: "CV", name: "Cabo Verde", flag: "🇨🇻", phone: "+238" },
  { code: "KH", name: "Cambodia", flag: "🇰🇭", phone: "+855" },
  { code: "CM", name: "Cameroon", flag: "🇨🇲", phone: "+237" },
  { code: "CA", name: "Canada", flag: "🇨🇦", phone: "+1", states: ["Alberta","British Columbia","Manitoba","New Brunswick","Newfoundland and Labrador","Northwest Territories","Nova Scotia","Nunavut","Ontario","Prince Edward Island","Quebec","Saskatchewan","Yukon"] },
  { code: "CF", name: "Central African Republic", flag: "🇨🇫", phone: "+236" },
  { code: "TD", name: "Chad", flag: "🇹🇩", phone: "+235" },
  { code: "CL", name: "Chile", flag: "🇨🇱", phone: "+56", states: ["Antofagasta","Araucanía","Arica and Parinacota","Atacama","Aysén","Biobío","Coquimbo","Los Lagos","Los Ríos","Magallanes","Maule","Metropolitana de Santiago","Ñuble","O'Higgins","Tarapacá","Valparaíso"] },
  { code: "CN", name: "China", flag: "🇨🇳", phone: "+86", states: ["Anhui","Beijing","Chongqing","Fujian","Gansu","Guangdong","Guangxi","Guizhou","Hainan","Hebei","Heilongjiang","Henan","Hong Kong","Hubei","Hunan","Inner Mongolia","Jiangsu","Jiangxi","Jilin","Liaoning","Macau","Ningxia","Qinghai","Shaanxi","Shandong","Shanghai","Shanxi","Sichuan","Tianjin","Tibet","Xinjiang","Yunnan","Zhejiang"] },
  { code: "CO", name: "Colombia", flag: "🇨🇴", phone: "+57", states: ["Amazonas","Antioquia","Arauca","Atlántico","Bolívar","Boyacá","Caldas","Caquetá","Casanare","Cauca","Cesar","Chocó","Córdoba","Cundinamarca","Guainía","Guaviare","Huila","La Guajira","Magdalena","Meta","Nariño","Norte de Santander","Putumayo","Quindío","Risaralda","San Andrés","Santander","Sucre","Tolima","Valle del Cauca","Vaupés","Vichada"] },
  { code: "KM", name: "Comoros", flag: "🇰🇲", phone: "+269" },
  { code: "CG", name: "Congo", flag: "🇨🇬", phone: "+242" },
  { code: "CD", name: "Congo (DRC)", flag: "🇨🇩", phone: "+243" },
  { code: "CR", name: "Costa Rica", flag: "🇨🇷", phone: "+506" },
  { code: "CI", name: "Côte d'Ivoire", flag: "🇨🇮", phone: "+225" },
  { code: "HR", name: "Croatia", flag: "🇭🇷", phone: "+385" },
  { code: "CU", name: "Cuba", flag: "🇨🇺", phone: "+53" },
  { code: "CY", name: "Cyprus", flag: "🇨🇾", phone: "+357" },
  { code: "CZ", name: "Czech Republic", flag: "🇨🇿", phone: "+420" },
  { code: "DK", name: "Denmark", flag: "🇩🇰", phone: "+45" },
  { code: "DJ", name: "Djibouti", flag: "🇩🇯", phone: "+253" },
  { code: "DM", name: "Dominica", flag: "🇩🇲", phone: "+1" },
  { code: "DO", name: "Dominican Republic", flag: "🇩🇴", phone: "+1" },
  { code: "EC", name: "Ecuador", flag: "🇪🇨", phone: "+593" },
  { code: "EG", name: "Egypt", flag: "🇪🇬", phone: "+20", states: ["Alexandria","Aswan","Asyut","Beheira","Beni Suef","Cairo","Dakahlia","Damietta","Faiyum","Gharbia","Giza","Ismailia","Kafr el-Sheikh","Luxor","Matruh","Minya","Monufia","New Valley","North Sinai","Port Said","Qalyubia","Qena","Red Sea","Sharqia","Sohag","South Sinai","Suez"] },
  { code: "SV", name: "El Salvador", flag: "🇸🇻", phone: "+503" },
  { code: "GQ", name: "Equatorial Guinea", flag: "🇬🇶", phone: "+240" },
  { code: "ER", name: "Eritrea", flag: "🇪🇷", phone: "+291" },
  { code: "EE", name: "Estonia", flag: "🇪🇪", phone: "+372" },
  { code: "SZ", name: "Eswatini", flag: "🇸🇿", phone: "+268" },
  { code: "ET", name: "Ethiopia", flag: "🇪🇹", phone: "+251", states: ["Addis Ababa","Afar","Amhara","Benishangul-Gumuz","Dire Dawa","Gambela","Harari","Oromia","Sidama","Somali","South West Ethiopia Peoples","Southern Nations","Tigray"] },
  { code: "FJ", name: "Fiji", flag: "🇫🇯", phone: "+679" },
  { code: "FI", name: "Finland", flag: "🇫🇮", phone: "+358" },
  { code: "FR", name: "France", flag: "🇫🇷", phone: "+33", states: ["Auvergne-Rhône-Alpes","Bourgogne-Franche-Comté","Bretagne","Centre-Val de Loire","Corse","Grand Est","Guadeloupe","Guyane","Hauts-de-France","Île-de-France","La Réunion","Martinique","Mayotte","Normandie","Nouvelle-Aquitaine","Occitanie","Pays de la Loire","Provence-Alpes-Côte d'Azur"] },
  { code: "GA", name: "Gabon", flag: "🇬🇦", phone: "+241" },
  { code: "GM", name: "Gambia", flag: "🇬🇲", phone: "+220" },
  { code: "GE", name: "Georgia", flag: "🇬🇪", phone: "+995" },
  { code: "DE", name: "Germany", flag: "🇩🇪", phone: "+49", states: ["Baden-Württemberg","Bavaria","Berlin","Brandenburg","Bremen","Hamburg","Hesse","Lower Saxony","Mecklenburg-Vorpommern","North Rhine-Westphalia","Rhineland-Palatinate","Saarland","Saxony","Saxony-Anhalt","Schleswig-Holstein","Thuringia"] },
  { code: "GH", name: "Ghana", flag: "🇬🇭", phone: "+233", states: ["Ahafo","Ashanti","Bono","Bono East","Central","Eastern","Greater Accra","North East","Northern","Oti","Savannah","Upper East","Upper West","Volta","Western","Western North"] },
  { code: "GR", name: "Greece", flag: "🇬🇷", phone: "+30" },
  { code: "GD", name: "Grenada", flag: "🇬🇩", phone: "+1" },
  { code: "GT", name: "Guatemala", flag: "🇬🇹", phone: "+502" },
  { code: "GN", name: "Guinea", flag: "🇬🇳", phone: "+224" },
  { code: "GW", name: "Guinea-Bissau", flag: "🇬🇼", phone: "+245" },
  { code: "GY", name: "Guyana", flag: "🇬🇾", phone: "+592" },
  { code: "HT", name: "Haiti", flag: "🇭🇹", phone: "+509" },
  { code: "HN", name: "Honduras", flag: "🇭🇳", phone: "+504" },
  { code: "HU", name: "Hungary", flag: "🇭🇺", phone: "+36" },
  { code: "IS", name: "Iceland", flag: "🇮🇸", phone: "+354" },
  { code: "IN", name: "India", flag: "🇮🇳", phone: "+91", states: ["Andaman and Nicobar Islands","Andhra Pradesh","Arunachal Pradesh","Assam","Bihar","Chandigarh","Chhattisgarh","Dadra and Nagar Haveli and Daman and Diu","Delhi","Goa","Gujarat","Haryana","Himachal Pradesh","Jammu and Kashmir","Jharkhand","Karnataka","Kerala","Ladakh","Lakshadweep","Madhya Pradesh","Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha","Puducherry","Punjab","Rajasthan","Sikkim","Tamil Nadu","Telangana","Tripura","Uttar Pradesh","Uttarakhand","West Bengal"] },
  { code: "ID", name: "Indonesia", flag: "🇮🇩", phone: "+62", states: ["Aceh","Bali","Bangka Belitung Islands","Banten","Bengkulu","Central Java","Central Kalimantan","Central Sulawesi","East Java","East Kalimantan","East Nusa Tenggara","Gorontalo","Jakarta","Jambi","Lampung","Maluku","North Kalimantan","North Maluku","North Sulawesi","North Sumatra","Papua","Riau","Riau Islands","South East Sulawesi","South Kalimantan","South Sulawesi","South Sumatra","Special Region of Yogyakarta","West Java","West Kalimantan","West Nusa Tenggara","West Papua","West Sulawesi","West Sumatra"] },
  { code: "IR", name: "Iran", flag: "🇮🇷", phone: "+98", states: ["Alborz","Ardabil","Bushehr","Chaharmahal and Bakhtiari","East Azerbaijan","Fars","Gilan","Golestan","Hamadan","Hormozgan","Ilam","Isfahan","Kerman","Kermanshah","Khuzestan","Kohgiluyeh and Boyer-Ahmad","Kurdestan","Lorestan","Markazi","Mazandaran","North Khorasan","Qazvin","Qom","Razavi Khorasan","Semnan","Sistan and Baluchestan","South Khorasan","Tehran","West Azerbaijan","Yazd","Zanjan"] },
  { code: "IQ", name: "Iraq", flag: "🇮🇶", phone: "+964", states: ["Al Anbar","Al Muthanna","Al-Qādisiyyah","Babylon","Baghdad","Basra","Dhi Qar","Diyala","Dohuk","Erbil","Halabja","Karbala","Kirkuk","Maysan","Najaf","Nineveh","Saladin","Sulaymaniyah","Wasit"] },
  { code: "IE", name: "Ireland", flag: "🇮🇪", phone: "+353", states: ["Carlow","Cavan","Clare","Cork","Donegal","Dublin","Galway","Kerry","Kildare","Kilkenny","Laois","Leitrim","Limerick","Longford","Louth","Mayo","Meath","Monaghan","Offaly","Roscommon","Sligo","Tipperary","Waterford","Westmeath","Wexford","Wicklow"] },
  { code: "IL", name: "Israel", flag: "🇮🇱", phone: "+972" },
  { code: "IT", name: "Italy", flag: "🇮🇹", phone: "+39", states: ["Abruzzo","Aosta Valley","Apulia","Basilicata","Calabria","Campania","Emilia-Romagna","Friuli Venezia Giulia","Lazio","Liguria","Lombardy","Marche","Molise","Piedmont","Sardinia","Sicily","Trentino-South Tyrol","Tuscany","Umbria","Veneto"] },
  { code: "JM", name: "Jamaica", flag: "🇯🇲", phone: "+1" },
  { code: "JP", name: "Japan", flag: "🇯🇵", phone: "+81", states: ["Aichi","Akita","Aomori","Chiba","Ehime","Fukui","Fukuoka","Fukushima","Gifu","Gunma","Hiroshima","Hokkaido","Hyogo","Ibaraki","Ishikawa","Iwate","Kagawa","Kagoshima","Kanagawa","Kochi","Kumamoto","Kyoto","Mie","Miyagi","Miyazaki","Nagano","Nagasaki","Nara","Niigata","Oita","Okayama","Okinawa","Osaka","Saga","Saitama","Shiga","Shimane","Shizuoka","Tochigi","Tokushima","Tokyo","Tottori","Toyama","Wakayama","Yamagata","Yamaguchi","Yamanashi"] },
  { code: "JO", name: "Jordan", flag: "🇯🇴", phone: "+962" },
  { code: "KZ", name: "Kazakhstan", flag: "🇰🇿", phone: "+7" },
  { code: "KE", name: "Kenya", flag: "🇰🇪", phone: "+254", states: ["Baringo","Bomet","Bungoma","Busia","Elgeyo-Marakwet","Embu","Garissa","Homa Bay","Isiolo","Kajiado","Kakamega","Kericho","Kiambu","Kilifi","Kirinyaga","Kisii","Kisumu","Kitui","Kwale","Laikipia","Lamu","Machakos","Makueni","Mandera","Marsabit","Meru","Migori","Mombasa","Murang'a","Nairobi","Nakuru","Nandi","Narok","Nyamira","Nyandarua","Nyeri","Samburu","Siaya","Taita-Taveta","Tana River","Tharaka-Nithi","Trans-Nzoia","Turkana","Uasin Gishu","Vihiga","Wajir","West Pokot"] },
  { code: "KI", name: "Kiribati", flag: "🇰🇮", phone: "+686" },
  { code: "KW", name: "Kuwait", flag: "🇰🇼", phone: "+965" },
  { code: "KG", name: "Kyrgyzstan", flag: "🇰🇬", phone: "+996" },
  { code: "LA", name: "Laos", flag: "🇱🇦", phone: "+856" },
  { code: "LV", name: "Latvia", flag: "🇱🇻", phone: "+371" },
  { code: "LB", name: "Lebanon", flag: "🇱🇧", phone: "+961" },
  { code: "LS", name: "Lesotho", flag: "🇱🇸", phone: "+266" },
  { code: "LR", name: "Liberia", flag: "🇱🇷", phone: "+231" },
  { code: "LY", name: "Libya", flag: "🇱🇾", phone: "+218" },
  { code: "LI", name: "Liechtenstein", flag: "🇱🇮", phone: "+423" },
  { code: "LT", name: "Lithuania", flag: "🇱🇹", phone: "+370" },
  { code: "LU", name: "Luxembourg", flag: "🇱🇺", phone: "+352" },
  { code: "MG", name: "Madagascar", flag: "🇲🇬", phone: "+261" },
  { code: "MW", name: "Malawi", flag: "🇲🇼", phone: "+265" },
  { code: "MY", name: "Malaysia", flag: "🇲🇾", phone: "+60", states: ["Federal Territory of Kuala Lumpur","Federal Territory of Labuan","Federal Territory of Putrajaya","Johor","Kedah","Kelantan","Melaka","Negeri Sembilan","Pahang","Perak","Perlis","Pulau Pinang","Sabah","Sarawak","Selangor","Terengganu"] },
  { code: "MV", name: "Maldives", flag: "🇲🇻", phone: "+960" },
  { code: "ML", name: "Mali", flag: "🇲🇱", phone: "+223" },
  { code: "MT", name: "Malta", flag: "🇲🇹", phone: "+356" },
  { code: "MH", name: "Marshall Islands", flag: "🇲🇭", phone: "+692" },
  { code: "MR", name: "Mauritania", flag: "🇲🇷", phone: "+222" },
  { code: "MU", name: "Mauritius", flag: "🇲🇺", phone: "+230" },
  { code: "MX", name: "Mexico", flag: "🇲🇽", phone: "+52", states: ["Aguascalientes","Baja California","Baja California Sur","Campeche","Chiapas","Chihuahua","Ciudad de México","Coahuila","Colima","Durango","Guanajuato","Guerrero","Hidalgo","Jalisco","México","Michoacán","Morelos","Nayarit","Nuevo León","Oaxaca","Puebla","Querétaro","Quintana Roo","San Luis Potosí","Sinaloa","Sonora","Tabasco","Tamaulipas","Tlaxcala","Veracruz","Yucatán","Zacatecas"] },
  { code: "FM", name: "Micronesia", flag: "🇫🇲", phone: "+691" },
  { code: "MD", name: "Moldova", flag: "🇲🇩", phone: "+373" },
  { code: "MC", name: "Monaco", flag: "🇲🇨", phone: "+377" },
  { code: "MN", name: "Mongolia", flag: "🇲🇳", phone: "+976" },
  { code: "ME", name: "Montenegro", flag: "🇲🇪", phone: "+382" },
  { code: "MA", name: "Morocco", flag: "🇲🇦", phone: "+212", states: ["Béni Mellal-Khénifra","Casablanca-Settat","Darâa-Tafilalet","Fès-Meknès","Guelmim-Oued Noun","Laâyoune-Sakia El Hamra","Marrakech-Safi","Oriental","Rabat-Salé-Kénitra","Souss-Massa","Tanger-Tétouan-Al Hoceïma"] },
  { code: "MZ", name: "Mozambique", flag: "🇲🇿", phone: "+258" },
  { code: "MM", name: "Myanmar", flag: "🇲🇲", phone: "+95", states: ["Ayeyarwady","Bago","Chin","Kachin","Kayah","Kayin","Magway","Mandalay","Mon","Naypyidaw Union Territory","Rakhine","Sagaing","Shan","Tanintharyi","Yangon"] },
  { code: "NA", name: "Namibia", flag: "🇳🇦", phone: "+264" },
  { code: "NR", name: "Nauru", flag: "🇳🇷", phone: "+674" },
  { code: "NP", name: "Nepal", flag: "🇳🇵", phone: "+977", states: ["Bagmati","Gandaki","Karnali","Koshi","Lumbini","Madhesh","Sudurpashchim"] },
  { code: "NL", name: "Netherlands", flag: "🇳🇱", phone: "+31", states: ["Drenthe","Flevoland","Friesland","Gelderland","Groningen","Limburg","North Brabant","North Holland","Overijssel","South Holland","Utrecht","Zeeland"] },
  { code: "NZ", name: "New Zealand", flag: "🇳🇿", phone: "+64", states: ["Auckland","Bay of Plenty","Canterbury","Gisborne","Hawke's Bay","Manawatu-Whanganui","Marlborough","Nelson","Northland","Otago","Southland","Taranaki","Tasman","Waikato","Wellington","West Coast"] },
  { code: "NI", name: "Nicaragua", flag: "🇳🇮", phone: "+505" },
  { code: "NE", name: "Niger", flag: "🇳🇪", phone: "+227" },
  { code: "NG", name: "Nigeria", flag: "🇳🇬", phone: "+234", states: ["Abia","Adamawa","Akwa Ibom","Anambra","Bauchi","Bayelsa","Benue","Borno","Cross River","Delta","Ebonyi","Edo","Ekiti","Enugu","FCT - Abuja","Gombe","Imo","Jigawa","Kaduna","Kano","Katsina","Kebbi","Kogi","Kwara","Lagos","Nasarawa","Niger","Ogun","Ondo","Osun","Oyo","Plateau","Rivers","Sokoto","Taraba","Yobe","Zamfara"] },
  { code: "KP", name: "North Korea", flag: "🇰🇵", phone: "+850" },
  { code: "MK", name: "North Macedonia", flag: "🇲🇰", phone: "+389" },
  { code: "NO", name: "Norway", flag: "🇳🇴", phone: "+47" },
  { code: "OM", name: "Oman", flag: "🇴🇲", phone: "+968" },
  { code: "PK", name: "Pakistan", flag: "🇵🇰", phone: "+92", states: ["Azad Kashmir","Balochistan","Federal Capital Territory","Gilgit-Baltistan","Khyber Pakhtunkhwa","Punjab","Sindh"] },
  { code: "PW", name: "Palau", flag: "🇵🇼", phone: "+680" },
  { code: "PA", name: "Panama", flag: "🇵🇦", phone: "+507" },
  { code: "PG", name: "Papua New Guinea", flag: "🇵🇬", phone: "+675" },
  { code: "PY", name: "Paraguay", flag: "🇵🇾", phone: "+595" },
  { code: "PE", name: "Peru", flag: "🇵🇪", phone: "+51" },
  { code: "PH", name: "Philippines", flag: "🇵🇭", phone: "+63", states: ["Bangsamoro","Bicol Region","Cagayan Valley","CALABARZON","Caraga","Central Luzon","Central Visayas","Cordillera Administrative Region","Davao Region","Eastern Visayas","Ilocos Region","Mimaropa","National Capital Region","Northern Mindanao","SOCCSKSARGEN","Western Visayas","Zamboanga Peninsula"] },
  { code: "PL", name: "Poland", flag: "🇵🇱", phone: "+48", states: ["Greater Poland","Holy Cross","Kuyavian-Pomeranian","Lesser Poland","Lodz","Lower Silesian","Lublin","Lubusz","Masovian","Opole","Podlaskie","Pomeranian","Silesian","Subcarpathian","Warmian-Masurian","West Pomeranian"] },
  { code: "PT", name: "Portugal", flag: "🇵🇹", phone: "+351" },
  { code: "QA", name: "Qatar", flag: "🇶🇦", phone: "+974" },
  { code: "RO", name: "Romania", flag: "🇷🇴", phone: "+40" },
  { code: "RU", name: "Russia", flag: "🇷🇺", phone: "+7", states: ["Altai Republic","Altai Krai","Amur Oblast","Arkhangelsk Oblast","Astrakhan Oblast","Belgorod Oblast","Bryansk Oblast","Buryatia","Chechen Republic","Chelyabinsk Oblast","Chukotka","Chuvashia","Dagestan","Ingushetia","Irkutsk Oblast","Ivanovo Oblast","Jewish Autonomous Oblast","Kabardino-Balkaria","Kaliningrad Oblast","Kalmykia","Kaluga Oblast","Kamchatka Krai","Karachay-Cherkessia","Karelia","Kemerovo Oblast","Kirov Oblast","Komi","Kostroma Oblast","Krasnodar Krai","Krasnoyarsk Krai","Kurgan Oblast","Kursk Oblast","Leningrad Oblast","Lipetsk Oblast","Magadan Oblast","Mari El","Mordovia","Moscow","Moscow Oblast","Murmansk Oblast","Nizhny Novgorod Oblast","North Ossetia-Alania","Novgorod Oblast","Novosibirsk Oblast","Omsk Oblast","Orenburg Oblast","Orel Oblast","Penza Oblast","Perm Krai","Primorsky Krai","Pskov Oblast","Rostov Oblast","Ryazan Oblast","Sakha (Yakutia)","Sakhalin Oblast","Samara Oblast","Saratov Oblast","Smolensk Oblast","St. Petersburg","Stavropol Krai","Sverdlovsk Oblast","Tambov Oblast","Tatarstan","Tomsk Oblast","Tula Oblast","Tuva","Tver Oblast","Tyumen Oblast","Udmurtia","Ulyanovsk Oblast","Vladimir Oblast","Volgograd Oblast","Vologda Oblast","Voronezh Oblast","Yakutia","Yaroslavl Oblast","Zabaykalsky Krai"] },
  { code: "RW", name: "Rwanda", flag: "🇷🇼", phone: "+250" },
  { code: "KN", name: "Saint Kitts and Nevis", flag: "🇰🇳", phone: "+1" },
  { code: "LC", name: "Saint Lucia", flag: "🇱🇨", phone: "+1" },
  { code: "VC", name: "Saint Vincent and the Grenadines", flag: "🇻🇨", phone: "+1" },
  { code: "WS", name: "Samoa", flag: "🇼🇸", phone: "+685" },
  { code: "SM", name: "San Marino", flag: "🇸🇲", phone: "+378" },
  { code: "ST", name: "São Tomé and Príncipe", flag: "🇸🇹", phone: "+239" },
  { code: "SA", name: "Saudi Arabia", flag: "🇸🇦", phone: "+966", states: ["Al Bahah","Al Jawf","Al Madinah","Al-Qassim","Asir","Eastern Province","Ha'il","Jizan","Makkah","Najran","Northern Borders","Riyadh","Tabuk"] },
  { code: "SN", name: "Senegal", flag: "🇸🇳", phone: "+221" },
  { code: "RS", name: "Serbia", flag: "🇷🇸", phone: "+381" },
  { code: "SC", name: "Seychelles", flag: "🇸🇨", phone: "+248" },
  { code: "SL", name: "Sierra Leone", flag: "🇸🇱", phone: "+232" },
  { code: "SG", name: "Singapore", flag: "🇸🇬", phone: "+65" },
  { code: "SK", name: "Slovakia", flag: "🇸🇰", phone: "+421" },
  { code: "SI", name: "Slovenia", flag: "🇸🇮", phone: "+386" },
  { code: "SB", name: "Solomon Islands", flag: "🇸🇧", phone: "+677" },
  { code: "SO", name: "Somalia", flag: "🇸🇴", phone: "+252" },
  { code: "ZA", name: "South Africa", flag: "🇿🇦", phone: "+27", states: ["Eastern Cape","Free State","Gauteng","KwaZulu-Natal","Limpopo","Mpumalanga","North West","Northern Cape","Western Cape"] },
  { code: "SS", name: "South Sudan", flag: "🇸🇸", phone: "+211" },
  { code: "KR", name: "South Korea", flag: "🇰🇷", phone: "+82", states: ["Busan","Chungcheongbuk-do","Chungcheongnam-do","Daegu","Daejeon","Gangwon-do","Gwangju","Gyeonggi-do","Gyeongsangbuk-do","Gyeongsangnam-do","Incheon","Jeju","Jeollabuk-do","Jeollanam-do","Sejong","Seoul","Ulsan"] },
  { code: "ES", name: "Spain", flag: "🇪🇸", phone: "+34", states: ["Andalusia","Aragon","Asturias","Balearic Islands","Basque Country","Canary Islands","Cantabria","Castile and León","Castile-La Mancha","Catalonia","Ceuta","Extremadura","Galicia","La Rioja","Madrid","Melilla","Murcia","Navarre","Valencia"] },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰", phone: "+94", states: ["Central","Eastern","North Central","North Western","Northern","Sabaragamuwa","Southern","Uva","Western"] },
  { code: "SD", name: "Sudan", flag: "🇸🇩", phone: "+249" },
  { code: "SR", name: "Suriname", flag: "🇸🇷", phone: "+597" },
  { code: "SE", name: "Sweden", flag: "🇸🇪", phone: "+46" },
  { code: "CH", name: "Switzerland", flag: "🇨🇭", phone: "+41", states: ["Aargau","Appenzell Ausserrhoden","Appenzell Innerrhoden","Basel-Landschaft","Basel-Stadt","Bern","Fribourg","Geneva","Glarus","Graubünden","Jura","Lucerne","Neuchâtel","Nidwalden","Obwalden","St. Gallen","Schaffhausen","Schwyz","Solothurn","Thurgau","Ticino","Uri","Valais","Vaud","Zug","Zurich"] },
  { code: "SY", name: "Syria", flag: "🇸🇾", phone: "+963" },
  { code: "TW", name: "Taiwan", flag: "🇹🇼", phone: "+886" },
  { code: "TJ", name: "Tajikistan", flag: "🇹🇯", phone: "+992" },
  { code: "TZ", name: "Tanzania", flag: "🇹🇿", phone: "+255", states: ["Arusha","Coast","Dar es Salaam","Dodoma","Geita","Iringa","Kagera","Katavi","Kigoma","Kilimanjaro","Lindi","Manyara","Mara","Mbeya","Morogoro","Mtwara","Mwanza","Njombe","Pemba North","Pemba South","Pwani","Rukwa","Ruvuma","Shinyanga","Simiyu","Singida","Songwe","Tabora","Tanga","Zanzibar North","Zanzibar South and Central","Zanzibar Urban/West"] },
  { code: "TH", name: "Thailand", flag: "🇹🇭", phone: "+66", states: ["Amnat Charoen","Ang Thong","Bangkok","Bueng Kan","Buri Ram","Chachoengsao","Chai Nat","Chaiyaphum","Chanthaburi","Chiang Mai","Chiang Rai","Chon Buri","Chumphon","Kalasin","Kamphaeng Phet","Kanchanaburi","Khon Kaen","Krabi","Lampang","Lamphun","Loei","Lop Buri","Mae Hong Son","Maha Sarakham","Mukdahan","Nakhon Nayok","Nakhon Pathom","Nakhon Phanom","Nakhon Ratchasima","Nakhon Sawan","Nakhon Si Thammarat","Nan","Narathiwat","Nong Bua Lam Phu","Nong Khai","Nonthaburi","Pathum Thani","Pattani","Phang Nga","Phatthalung","Phayao","Phetchabun","Phetchaburi","Phichit","Phitsanulok","Phra Nakhon Si Ayutthaya","Phrae","Phuket","Prachin Buri","Prachuap Khiri Khan","Ranong","Ratchaburi","Rayong","Roi Et","Sa Kaeo","Sakon Nakhon","Samut Prakan","Samut Sakhon","Samut Songkhram","Saraburi","Satun","Sing Buri","Sisaket","Songkhla","Sukhothai","Suphan Buri","Surat Thani","Surin","Tak","Trang","Trat","Ubon Ratchathani","Udon Thani","Uthai Thani","Uttaradit","Yala","Yasothon"] },
  { code: "TL", name: "Timor-Leste", flag: "🇹🇱", phone: "+670" },
  { code: "TG", name: "Togo", flag: "🇹🇬", phone: "+228" },
  { code: "TO", name: "Tonga", flag: "🇹🇴", phone: "+676" },
  { code: "TT", name: "Trinidad and Tobago", flag: "🇹🇹", phone: "+1" },
  { code: "TN", name: "Tunisia", flag: "🇹🇳", phone: "+216" },
  { code: "TR", name: "Turkey", flag: "🇹🇷", phone: "+90", states: ["Adana","Adıyaman","Afyonkarahisar","Ağrı","Aksaray","Amasya","Ankara","Antalya","Ardahan","Artvin","Aydın","Balıkesir","Bartın","Batman","Bayburt","Bilecik","Bingöl","Bitlis","Bolu","Burdur","Bursa","Çanakkale","Çankırı","Çorum","Denizli","Diyarbakır","Düzce","Edirne","Elazığ","Erzincan","Erzurum","Eskişehir","Gaziantep","Giresun","Gümüşhane","Hakkari","Hatay","Iğdır","Isparta","Istanbul","İzmir","Kahramanmaraş","Karabük","Karaman","Kars","Kastamonu","Kayseri","Kilis","Kırıkkale","Kırklareli","Kırşehir","Kocaeli","Konya","Kütahya","Malatya","Manisa","Mardin","Mersin","Muğla","Muş","Nevşehir","Niğde","Ordu","Osmaniye","Rize","Sakarya","Samsun","Şanlıurfa","Siirt","Sinop","Şırnak","Sivas","Tekirdağ","Tokat","Trabzon","Tunceli","Uşak","Van","Yalova","Yozgat","Zonguldak"] },
  { code: "TM", name: "Turkmenistan", flag: "🇹🇲", phone: "+993" },
  { code: "TV", name: "Tuvalu", flag: "🇹🇻", phone: "+688" },
  { code: "UG", name: "Uganda", flag: "🇺🇬", phone: "+256" },
  { code: "UA", name: "Ukraine", flag: "🇺🇦", phone: "+380" },
  { code: "AE", name: "United Arab Emirates", flag: "🇦🇪", phone: "+971", states: ["Abu Dhabi","Ajman","Dubai","Fujairah","Ras Al Khaimah","Sharjah","Umm Al Quwain"] },
  { code: "GB", name: "United Kingdom", flag: "🇬🇧", phone: "+44", states: ["Bedfordshire","Berkshire","Bristol","Buckinghamshire","Cambridgeshire","Cheshire","City of London","Cornwall","Cumbria","Derbyshire","Devon","Dorset","Durham","East Riding of Yorkshire","East Sussex","Essex","Gloucestershire","Greater London","Greater Manchester","Hampshire","Herefordshire","Hertfordshire","Isle of Wight","Kent","Lancashire","Leicestershire","Lincolnshire","Merseyside","Middlesex","Norfolk","North Yorkshire","Northamptonshire","Northumberland","Nottinghamshire","Oxfordshire","Rutland","Shropshire","Somerset","South Yorkshire","Staffordshire","Suffolk","Surrey","Tyne and Wear","Warwickshire","West Midlands","West Sussex","West Yorkshire","Wiltshire","Worcestershire","Northern Ireland","Scotland","Wales"] },
  { code: "US", name: "United States", flag: "🇺🇸", phone: "+1", states: ["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","Washington D.C.","West Virginia","Wisconsin","Wyoming"] },
  { code: "UY", name: "Uruguay", flag: "🇺🇾", phone: "+598" },
  { code: "UZ", name: "Uzbekistan", flag: "🇺🇿", phone: "+998" },
  { code: "VU", name: "Vanuatu", flag: "🇻🇺", phone: "+678" },
  { code: "VE", name: "Venezuela", flag: "🇻🇪", phone: "+58" },
  { code: "VN", name: "Vietnam", flag: "🇻🇳", phone: "+84", states: ["An Giang","Ba Ria-Vung Tau","Bac Giang","Bac Kan","Bac Lieu","Bac Ninh","Ben Tre","Binh Dinh","Binh Duong","Binh Phuoc","Binh Thuan","Ca Mau","Can Tho","Cao Bang","Da Nang","Dak Lak","Dak Nong","Dien Bien","Dong Nai","Dong Thap","Gia Lai","Ha Giang","Ha Nam","Ha Noi","Ha Tinh","Hai Duong","Hai Phong","Hau Giang","Ho Chi Minh City","Hoa Binh","Hung Yen","Khanh Hoa","Kien Giang","Kon Tum","Lai Chau","Lam Dong","Lang Son","Lao Cai","Long An","Nam Dinh","Nghe An","Ninh Binh","Ninh Thuan","Phu Tho","Phu Yen","Quang Binh","Quang Nam","Quang Ngai","Quang Ninh","Quang Tri","Soc Trang","Son La","Tay Ninh","Thai Binh","Thai Nguyen","Thanh Hoa","Thua Thien Hue","Tien Giang","Tra Vinh","Tuyen Quang","Vinh Long","Vinh Phuc","Yen Bai"] },
  { code: "YE", name: "Yemen", flag: "🇾🇪", phone: "+967" },
  { code: "ZM", name: "Zambia", flag: "🇿🇲", phone: "+260" },
  { code: "ZW", name: "Zimbabwe", flag: "🇿🇼", phone: "+263" },
]

export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find((c) => c.code === code)
}
